### ISSUE TITLE
console.assert is not a function

### ISSUE THREAD

**Issue by BarinderGrewal** [mysticatea/event-target-shim#28]
**Overview**
I have a react native app which I am running on android.
I have event-target-shim as a dependency.

**Issue**
The app was working fine with react-native version 0.59.
But when I upgraded it to react-native version 0.60, I started seeing an error
`"console.assert is not a function"`

When I remove console.assert statement from line 46 of [event-target-shim.js](https://github.com/mysticatea/event-target-shim/blob/master/dist/event-target-shim.js), everything works fine.

**Comment by mysticatea** [comment]
Thank you for your report.

But I think that this is not a problem of `event-target-shim` because the `console.assert` is [standardized in the web standard](https://console.spec.whatwg.org/#assert) and is in [Node.js](https://nodejs.org/api/console.html#console_console_assert_value_message). Would you open an issue on React Native?

**Comment by BarinderGrewal** [comment]
Thanks for the response.
I will close this issue and open another one on React Native.
